asyncapi: '2.6.0'
info:
  title: Bank Argent API
  version: '1.0.0'
  description: |
    API permettant la gestion des transactions bancaires.

    ### Fonctionnalités principales :
    * Récupérer les transactions du mois en cours
    * Gérer les transactions spécifiques
    * Supprimer des transactions
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
servers:
  local:
    url: localhost:3001
    protocol: http
    description: Serveur local pour le développement
    tags:
      - name: "env:local"
        description: "Environnement de développement local"
defaultContentType: application/json
channels:
  transactions.get:
    description: Récupération des transactions du mois en cours
    subscribe:
      summary: Obtenir toutes les transactions du mois en cours
      operationId: getTransactions
      message:
        $ref: '#/components/messages/TransactionList'
  transactions.{transactionId}.get:
    description: Récupération des détails d'une transaction
    parameters:
      transactionId:
        $ref: '#/components/parameters/transactionId'
    subscribe:
      summary: Obtenir les détails d'une transaction spécifique
      operationId: getTransactionDetails
      message:
        $ref: '#/components/messages/TransactionDetails'
  transactions.{transactionId}.put:
    description: Mise à jour des informations d'une transaction
    parameters:
      transactionId:
        $ref: '#/components/parameters/transactionId'
    publish:
      summary: Mettre à jour une transaction
      operationId: updateTransaction
      message:
        $ref: '#/components/messages/UpdateTransaction'
  transactions.{transactionId}.delete:
    description: Suppression d'une transaction
    parameters:
      transactionId:
        $ref: '#/components/parameters/transactionId'
    publish:
      summary: Supprimer une transaction
      operationId: deleteTransaction
      message:
        $ref: '#/components/messages/DeleteTransaction'
components:
  messages:
    TransactionList:
      name: TransactionList
      summary: Liste des transactions du mois en cours
      contentType: application/json
      payload:
        type: array
        items:
          $ref: '#/components/schemas/Transaction'
    TransactionDetails:
      name: TransactionDetails
      summary: Détails d'une transaction spécifique
      contentType: application/json
      payload:
        $ref: '#/components/schemas/TransactionDetails'
    UpdateTransaction:
      name: UpdateTransaction
      summary: Mise à jour d'une transaction
      contentType: application/json
      payload:
        type: object
        properties:
          category:
            type: string
          notes:
            type: string
    DeleteTransaction:
      name: DeleteTransaction
      summary: Suppression d'une transaction
      contentType: application/json
  schemas:
    Transaction:
      type: object
      properties:
        id:
          type: string
        date:
          type: string
          format: date
        description:
          type: string
        amount:
          type: number
          format: float
        balance:
          type: number
          format: float
        accountId:
          type: string
    TransactionDetails:
      type: object
      allOf:
        - $ref: '#/components/schemas/Transaction'
        - type: object
          properties:
            category:
              type: string
            notes:
              type: string
  parameters:
    transactionId:
      description: L'identifiant unique de la transaction.
      schema:
        type: string
