swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: http://127.0.0.1:5173/
basePath: /api/v1
schemes:
  - http
paths:
  /transactions:
    get:
      summary: Obtenir toutes les transactions du mois en cours
      description: Récupère toutes les transactions pour le mois en cours, groupées par compte bancaire.
      parameters:
        - in: query
          name: accountId
          schema:
            type: string
          required: true
          description: L'identifiant du compte bancaire.
        - in: query
          name: month
          schema:
            type: string
            format: date
          required: false
          description: Mois et année (YYYY-MM) pour filtrer les transactions. Par défaut, utilise le mois en cours.
      responses:
        '200':
          description: Liste des transactions récupérées avec succès.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transaction'
        '400':
          description: Requête invalide (ex. : accountId manquant).
        '404':
          description: Aucun compte ou transaction trouvé pour l'identifiant fourni.
  /transactions/{transactionId}:
    get:
      summary: Obtenir les détails d'une transaction
      description: Récupère les détails d'une transaction spécifique.
      parameters:
        - in: path
          name: transactionId
          schema:
            type: string
          required: true
          description: L'identifiant unique de la transaction.
      responses:
        '200':
          description: Détails de la transaction récupérés avec succès.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionDetails'
        '404':
          description: Transaction non trouvée.
    put:
      summary: Mettre à jour les informations d'une transaction
      description: Permet de mettre à jour la catégorie ou les notes d'une transaction.
      parameters:
        - in: path
          name: transactionId
          schema:
            type: string
          required: true
          description: L'identifiant unique de la transaction.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                category:
                  type: string
                  description: Nouvelle catégorie de la transaction.
                notes:
                  type: string
                  description: Nouvelle note pour la transaction.
      responses:
        '200':
          description: Transaction mise à jour avec succès.
        '400':
          description: Erreur dans les données fournies.
        '404':
          description: Transaction non trouvée.
    delete:
      summary: Supprimer une transaction
      description: Permet de supprimer une transaction spécifique.
      parameters:
        - in: path
          name: transactionId
          schema:
            type: string
          required: true
          description: L'identifiant unique de la transaction.
      responses:
        '204':
          description: Transaction supprimée avec succès (pas de contenu renvoyé).
        '404':
          description: Transaction non trouvée.
components:
  schemas:
    Transaction:
      type: object
      properties:
        id:
          type: string
          description: Identifiant unique de la transaction.
        date:
          type: string
          format: date
          description: Date de la transaction.
        description:
          type: string
          description: Description ou nom du commerçant.
        amount:
          type: number
          format: float
          description: Montant de la transaction.
        balance:
          type: number
          format: float
          description: Solde restant après cette transaction.
        accountId:
          type: string
          description: Identifiant du compte lié à cette transaction.
    TransactionDetails:
      type: object
      allOf:
        - $ref: '#/components/schemas/Transaction'
        - type: object
          properties:
            category:
              type: string
              description: Catégorie assignée à la transaction.
            notes:
              type: string
              description: Notes ajoutées par l'utilisateur.